"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Bird, CheckCircle2, ChevronDown, Leaf, MapPin, MessageSquare, Microscope, Search, ShieldCheck, Sparkles, ThumbsDown, ThumbsUp, TreePine } from "lucide-react";
import { Logo } from "../../components/app/logo";

type Status = "Specialist verified" | "Mentor reviewed" | "AI suggestion";
type Category = "All" | "Plants" | "Animals" | "Microbial";
type RecordItem = { id:string; common:string; scientific:string; category:Exclude<Category,"All">; status:Status; confidence?:number; school:string; place:string; date:string; note:string; icon:typeof Leaf; tone:string; x:number; y:number; latitude:number; longitude:number };

const demoRecords: RecordItem[] = [
  {id:"GMA-0294",common:"African tulip tree",scientific:"Spathodea campanulata",category:"Plants",status:"Specialist verified",school:"Staff School",place:"Ibadan, Nigeria",date:"28 Aug 2026",note:"Mature tree mapped beside the assembly lawn. Flowers observed attracting sunbirds.",icon:TreePine,tone:"from-[#193f32] to-[#718a4c]",x:43,y:47},
  {id:"GMA-0301",common:"Plain tiger butterfly",scientific:"Danaus chrysippus",category:"Animals",status:"Mentor reviewed",school:"Bodija College",place:"Ibadan, Nigeria",date:"29 Aug 2026",note:"Four-minute observation on milkweed. Wing pattern is consistent; specialist review requested.",icon:Bird,tone:"from-[#6a3d24] to-[#d48635]",x:61,y:58},
  {id:"GMA-0308",common:"Neem",scientific:"Azadirachta indica",category:"Plants",status:"AI suggestion",confidence:76,school:"Community Primary",place:"Oyo State, Nigeria",date:"30 Aug 2026",note:"Young roadside tree. Leaf and bark photographs need a clearer scale reference.",icon:Leaf,tone:"from-[#174c39] to-[#9bb857]",x:31,y:65},
  {id:"GMA-0310",common:"Soil fungal network",scientific:"Identification pending",category:"Microbial",status:"AI suggestion",confidence:51,school:"University Demo School",place:"Ibadan, Nigeria",date:"30 Aug 2026",note:"Classroom microscope image from moist leaf litter. Culture or microscopy review is needed.",icon:Microscope,tone:"from-[#324c50] to-[#89aaa2]",x:70,y:34},
  {id:"GMA-0314",common:"Village weaver",scientific:"Ploceus cucullatus",category:"Animals",status:"Specialist verified",school:"Greenfield School",place:"Ibadan, Nigeria",date:"30 Aug 2026",note:"Adult male photographed near two suspended nests; location generalized for wildlife protection.",icon:Bird,tone:"from-[#343153] to-[#b1a54f]",x:52,y:42},
  {id:"GMA-0318",common:"Sensitive fern",scientific:"Onoclea sensibilis",category:"Plants",status:"Mentor reviewed",school:"Lakeside Secondary",place:"Lagos, Nigeria",date:"30 Aug 2026",note:"Observed in a shaded damp area. Mentor recommends checking sori before confirmation.",icon:Leaf,tone:"from-[#20493e] to-[#65a67b]",x:37,y:31},
];

const statusStyle: Record<Status,string> = {
  "Specialist verified":"bg-emerald-100 text-emerald-800",
  "Mentor reviewed":"bg-indigo-100 text-indigo-800",
  "AI suggestion":"bg-amber-100 text-amber-900",
};

export function ObservationsExplorer() {
  const [records, setRecords] = useState<RecordItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [category,setCategory] = useState<Category>("All");
  const [query,setQuery] = useState("");
  const [selected,setSelected] = useState<string | null>(null);
  const [votes,setVotes] = useState({agree:18,disagree:2,user:""});
  useEffect(() => {
    void fetch("/api/public/observations")
      .then(async response => response.ok ? response.json() : { records: [] })
      .then(({ records: liveRecords = [] }) => {
        const typedRecords = (liveRecords as Array<RecordItem & { category: Exclude<Category,"All"> }>).map((record, index, all) => {
          const latitudes = all.map(item => item.latitude);
          const longitudes = all.map(item => item.longitude);
          const minLat = Math.min(...latitudes);
          const minLon = Math.min(...longitudes);
          const latRange = Math.max(Math.max(...latitudes) - minLat, 0.000001);
          const lonRange = Math.max(Math.max(...longitudes) - minLon, 0.000001);
          const icon = record.category === "Plants" ? Leaf : record.category === "Microbial" ? Microscope : Bird;
          return { ...record, status: "Specialist verified" as const, icon, tone: "from-[#193f32] to-[#718a4c]", x: 10 + ((record.longitude - minLon) / lonRange) * 80, y: 82 - ((record.latitude - minLat) / latRange) * 64 };
        });
        setRecords(typedRecords);
        setSelected(typedRecords[0]?.id ?? null);
      })
      .catch(() => setRecords([]))
      .finally(() => setLoading(false));
  }, []);
  const filtered = useMemo(() => records.filter(r => (category === "All" || r.category === category) && `${r.common} ${r.scientific} ${r.school}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
  const active = records.find(r => r.id === selected) || records[0] || ({} as RecordItem);
  const vote = (choice:"agree"|"disagree") => setVotes(v => ({...v,[choice]:v[choice] + (v.user === choice ? -1 : 1), ...(v.user && v.user !== choice ? {[v.user]:v[v.user as "agree"|"disagree"]-1}:{}),user:v.user === choice ? "" : choice}));

  return <main className="min-h-screen bg-[#f2f3ed] text-[#17332c]"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#082f27] px-4 py-3.5 text-white sm:px-7"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><Logo /><nav className="flex items-center gap-2 text-[11px] font-bold"><Link className="hidden rounded-md px-3 py-2 text-emerald-100/70 sm:block" href="/">Home</Link><Link className="rounded-md bg-lime-300 px-4 py-2.5 text-emerald-950" href="/field">Add observation</Link></nav></div></header>
    <section className="border-b border-slate-200 bg-white px-4 py-12 sm:px-7"><div className="mx-auto max-w-[1500px]"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">PUBLIC BIODIVERSITY COMMONS</p><div className="mt-3 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h1 className="font-serif text-5xl leading-tight text-emerald-950 sm:text-6xl">Evidence, not just identifications.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Explore observations from registered schools and Geo-Mentors. Every record shows what AI suggested, what people reviewed and what remains uncertain.</p></div><div className="flex gap-2"><span className="rounded-xl bg-[#f2f3ed] px-5 py-3 text-center"><b className="block font-serif text-2xl">2,846</b><small className="text-[8px] font-black text-slate-400">PUBLIC RECORDS</small></span><span className="rounded-xl bg-emerald-950 px-5 py-3 text-center text-white"><b className="block font-serif text-2xl">61%</b><small className="text-[8px] font-black text-emerald-100/55">VERIFIED</small></span></div></div></div></section>
    <section className="px-4 py-6 sm:px-7"><div className="mx-auto max-w-[1500px]"><div className="grid overflow-hidden rounded-2xl border border-slate-200 bg-white lg:grid-cols-[1.45fr_.55fr]"><div className="relative min-h-[390px] overflow-hidden bg-[#d7e2cd]"><div className="absolute inset-0 opacity-35 [background-image:radial-gradient(#577563_1px,transparent_1px)] [background-size:20px_20px]" /><div className="absolute left-[15%] top-[13%] h-[70%] w-[70%] rounded-[43%_54%_45%_52%] bg-[#bfd1b4] shadow-inner" />{records.map(r => <button key={r.id} onClick={() => setSelected(r.id)} className={`absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white shadow-lg transition ${selected === r.id ? "size-12 bg-lime-400 text-emerald-950 ring-4 ring-emerald-900/20" : "size-9 bg-emerald-800 text-white"}`} style={{left:`${r.x}%`,top:`${r.y}%`}} aria-label={`Open ${r.common}`}><MapPin className="mx-auto size-4" /></button>)}<div className="absolute bottom-4 left-4 rounded-lg bg-white/90 px-3 py-2 text-[9px] font-bold text-slate-500"><ShieldCheck className="mr-1 inline size-3.5 text-emerald-700" />School locations generalized · wildlife locations protected</div></div><aside className="p-6"><span className={`inline-flex rounded-full px-3 py-2 text-[9px] font-black ${statusStyle[active.status]}`}>{active.status}</span><p className="mt-5 text-[9px] font-black tracking-[.15em] text-slate-400">{active.id} · {active.place}</p><h2 className="mt-2 font-serif text-3xl text-emerald-950">{active.common}</h2><p className="mt-1 text-xs italic text-slate-500">{active.scientific}</p><p className="mt-5 text-xs leading-6 text-slate-600">{active.note}</p><div className="mt-6 border-t border-slate-100 pt-5 text-[10px]"><span className="text-slate-400">Recorded by</span><strong className="block text-emerald-950">{active.school}</strong></div><button className="mt-5 w-full rounded-lg bg-emerald-950 px-4 py-3 text-xs font-black text-white">Open full evidence record</button></aside></div>
      <div className="mt-6 flex flex-col justify-between gap-3 lg:flex-row"><label className="flex min-h-11 min-w-0 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 lg:w-[360px]"><Search className="size-4 text-slate-400" /><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-xs outline-none" placeholder="Search species or school" /></label><div className="flex flex-wrap gap-2">{(["All","Plants","Animals","Microbial"] as Category[]).map(c => <button key={c} onClick={()=>setCategory(c)} className={`rounded-lg px-4 py-3 text-[10px] font-black ${category===c?"bg-emerald-950 text-white":"border border-slate-200 bg-white text-slate-600"}`}>{c}</button>)}</div></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r => { const Icon=r.icon; return <article key={r.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white"><button className={`relative block h-48 w-full overflow-hidden bg-gradient-to-br ${r.tone}`} onClick={()=>setSelected(r.id)}><Icon className="absolute bottom-[-14px] right-[-8px] size-40 text-white/12" /><span className="absolute left-5 top-5 grid size-12 place-items-center rounded-full border border-white/20 bg-black/15 text-white backdrop-blur"><Icon className="size-5" /></span><span className="absolute bottom-4 left-4 rounded-md bg-white/90 px-2 py-1 text-[8px] font-black text-emerald-950">PHOTO EVIDENCE AVAILABLE</span></button><div className="p-5"><div className="flex items-center justify-between gap-2"><span className={`rounded-full px-2.5 py-1.5 text-[8px] font-black ${statusStyle[r.status]}`}>{r.status}</span>{r.confidence && <span className="text-[9px] font-bold text-amber-700">{r.confidence}% AI confidence</span>}</div><h3 className="mt-4 font-serif text-2xl text-emerald-950">{r.common}</h3><p className="mt-1 text-[10px] italic text-slate-400">{r.scientific}</p><p className="mt-4 line-clamp-2 text-[11px] leading-5 text-slate-500">{r.note}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-[9px]"><span><b className="block text-emerald-950">{r.school}</b><small className="text-slate-400">{r.place}</small></span><button onClick={()=>setSelected(r.id)} className="font-black text-emerald-700">Review →</button></div></div></article>})}</div>
      {filtered.length===0 && <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500">No records match this search.</div>}
      <section className="mt-8 grid overflow-hidden rounded-2xl border border-slate-200 bg-white lg:grid-cols-[.72fr_1.28fr]"><div className="bg-[#0b4436] p-7 text-white"><MessageSquare className="size-7 text-lime-300" /><p className="mt-7 text-[9px] font-black tracking-[.16em] text-lime-200">MENTOR REVIEW DISCUSSION</p><h2 className="mt-3 font-serif text-3xl">Corrections become part of the learning record.</h2><p className="mt-4 text-xs leading-6 text-emerald-50/65">Verified Geo-Mentors and specialists can comment on evidence. Community agreement helps surface useful reports, but does not replace an accountable verification decision.</p></div><div className="p-7"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-lime-100 text-[10px] font-black text-emerald-900">KA</span><div><div className="flex flex-wrap items-center gap-2"><strong className="text-xs">Dr Kemi Adeyemi</strong><span className="flex items-center gap-1 text-[8px] font-black text-emerald-700"><BadgeCheck className="size-3" />VERIFIED GEO-MENTOR</span></div><p className="mt-3 text-xs leading-6 text-slate-600">The wing margins and body pattern support <em>Danaus chrysippus</em>. I agree with the likely identification, but recommend one dorsal-wing photograph before specialist confirmation.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>vote("agree")} className={`flex items-center gap-2 rounded-full px-3 py-2 text-[9px] font-black ${votes.user==="agree"?"bg-emerald-800 text-white":"bg-emerald-50 text-emerald-800"}`}><ThumbsUp className="size-3.5" />Agree with report · {votes.agree}</button><button onClick={()=>vote("disagree")} className={`flex items-center gap-2 rounded-full px-3 py-2 text-[9px] font-black ${votes.user==="disagree"?"bg-rose-700 text-white":"bg-rose-50 text-rose-700"}`}><ThumbsDown className="size-3.5" />Disagree · {votes.disagree}</button></div></div></div><button className="mt-6 flex w-full items-center justify-between border-t border-slate-100 pt-5 text-[10px] font-black text-slate-500">View 4 more review notes <ChevronDown className="size-4" /></button></div></section>
    </div></section>
  </main>;
}
