"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpenCheck, Camera, Check, CheckCircle2, ClipboardCheck, Leaf, MapPin, Save, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "../../../components/app/logo";

const tasks = [
  { id: "observe", title: "Observe carefully", text: "Choose one plant, pollinator or habitat inside the teacher-approved area.", icon: Leaf },
  { id: "evidence", title: "Capture evidence", text: "Take a clear photograph without showing another student’s face or personal information.", icon: Camera },
  { id: "location", title: "Check location quality", text: "Record location only while supervised. Sensitive locations remain restricted.", icon: MapPin },
  { id: "notes", title: "Describe what happened", text: "Write what you saw, where it was and how the organism behaved.", icon: ClipboardCheck },
];
const storageKey = "geomentor-student-mission-v1";

export function MissionLesson() {
  const [completed, setCompleted] = useState<string[]>([]);
  const [safetyReady, setSafetyReady] = useState(false);
  const [reflection, setReflection] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) || "{}"); setCompleted(saved.completed || []); setSafetyReady(Boolean(saved.safetyReady)); setReflection(saved.reflection || ""); } catch {} }, []);
  const progress = useMemo(() => Math.round((completed.length / tasks.length) * 100), [completed]);
  function toggle(id: string) { setCompleted((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); setMessage(null); }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); localStorage.setItem(storageKey, JSON.stringify({ completed, safetyReady, reflection })); setMessage(completed.length === tasks.length && safetyReady ? "Mission ready for teacher review. Your progress is saved on this device until live student records are activated." : "Progress saved on this device. Complete the safety check and all mission tasks before teacher review."); }

  return <main className="min-h-screen bg-[#f4f6f1] text-[#15342d]">
    <header className="border-b border-white/10 bg-[#0b4436] px-4 py-4 text-white sm:px-7"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Logo /><Link href="/student" className="rounded-lg bg-white/10 px-4 py-2.5 text-xs font-bold">Student workspace</Link></div></header>
    <section className="bg-[radial-gradient(circle_at_85%_18%,rgba(202,230,105,.2),transparent_28%),linear-gradient(145deg,#0b4436,#153b31)] px-4 py-12 text-white sm:px-7"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-lime-200"><Sparkles className="size-4" />MISSION 01 · BIODIVERSITY BASELINE</span><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-tight">Discover one living neighbour.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-emerald-50/75">Observe one organism or habitat in your school’s approved field area, collect respectful evidence and explain what you discovered.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5"><div className="flex justify-between text-xs"><strong>Mission progress</strong><span>{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><span className="block h-full rounded-full bg-lime-300 transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-[10px] text-emerald-100/65">{completed.length} of {tasks.length} fieldwork steps completed</p></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-6 px-4 py-8 sm:px-7 lg:grid-cols-[minmax(0,1fr)_340px]"><form onSubmit={save} className="grid gap-5">
      <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 sm:p-6"><div className="flex gap-3"><ShieldCheck className="size-7 shrink-0 text-amber-700" /><div><p className="text-[10px] font-black tracking-[.16em] text-amber-800">SAFETY GATE</p><h2 className="mt-1 font-serif text-2xl text-amber-950">Check with your teacher before you begin.</h2><p className="mt-2 text-xs leading-5 text-amber-900/75">Stay inside the approved area, work with your assigned group, do not touch unknown organisms and never photograph people without permission.</p></div></div><label className="mt-5 flex cursor-pointer gap-3 rounded-xl border border-amber-300 bg-white/60 p-4 text-xs font-bold text-amber-950"><input required type="checkbox" className="mt-0.5 size-4 accent-emerald-700" checked={safetyReady} onChange={(e) => setSafetyReady(e.target.checked)} /><span>My teacher has approved this activity and I understand the safety instructions.</span></label></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><p className="text-[10px] font-black tracking-[.16em] text-emerald-700">YOUR FIELDWORK STEPS</p><h2 className="mt-2 font-serif text-3xl text-emerald-950">Complete the mission</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{tasks.map(({ id,title,text,icon:Icon }, index) => { const done = completed.includes(id); return <button key={id} type="button" onClick={() => toggle(id)} aria-pressed={done} className={`min-h-44 rounded-2xl border p-5 text-left transition ${done ? "border-emerald-600 bg-emerald-50" : "border-slate-200 hover:border-emerald-300"}`}><div className="flex items-center justify-between"><span className={`grid size-11 place-items-center rounded-xl ${done ? "bg-emerald-700 text-white" : "bg-lime-100 text-emerald-800"}`}>{done ? <Check className="size-5" /> : <Icon className="size-5" />}</span><span className="font-mono text-[10px] font-black text-slate-400">0{index + 1}</span></div><h3 className="mt-4 font-serif text-xl text-emerald-950">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></button>; })}</div><Link href="/field" className="mt-5 inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[#0b4436] px-5 text-xs font-black text-white">Open observation recorder <ArrowRight className="size-4" /></Link></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex gap-3"><BookOpenCheck className="size-6 text-emerald-700" /><div><p className="text-[10px] font-black tracking-[.16em] text-emerald-700">LEARNING REFLECTION</p><h2 className="mt-1 font-serif text-2xl text-emerald-950">What did you notice?</h2></div></div><label className="mt-5 grid gap-2 text-xs font-bold text-slate-700"><span>Write one discovery or question for your teacher</span><textarea required minLength={10} maxLength={600} value={reflection} onChange={(e) => { setReflection(e.target.value); setMessage(null); }} className="min-h-32 rounded-xl border border-slate-300 p-4 text-sm font-normal outline-none focus:border-emerald-600" placeholder="I noticed that… I wonder why…" /></label>{message && <div role="status" className="mt-4 rounded-xl bg-emerald-50 p-4 text-xs leading-5 text-emerald-900">{message}</div>}<button type="submit" className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-lime-300 px-5 text-xs font-black text-emerald-950"><Save className="size-4" />Save mission progress</button></section>
    </form><aside className="lg:sticky lg:top-6 lg:self-start"><article className="rounded-2xl border border-slate-200 bg-white p-6"><CheckCircle2 className="size-7 text-emerald-700" /><p className="mt-5 text-[10px] font-black tracking-[.16em] text-emerald-700">SUCCESS CRITERIA</p><h2 className="mt-2 font-serif text-2xl text-emerald-950">A strong observation is…</h2><ul className="mt-5 grid gap-3 text-xs leading-5 text-slate-600">{["Safe and teacher supervised","Inside the approved field area","Supported by a clear photograph","Described in your own words","Submitted for teacher review first"].map((item) => <li key={item} className="flex gap-3"><Check className="size-4 shrink-0 text-emerald-700" />{item}</li>)}</ul></article><article className="mt-4 rounded-2xl bg-emerald-950 p-6 text-white"><p className="text-[10px] font-black tracking-[.16em] text-lime-300">WHAT HAPPENS NEXT?</p><h2 className="mt-2 font-serif text-2xl">Teacher quality gate</h2><p className="mt-3 text-xs leading-5 text-emerald-50/70">Your teacher checks safety, evidence and learning quality. Only approved observations move to a verified expert for scientific identification.</p></article><p className="mt-3 rounded-xl bg-amber-50 p-4 text-[10px] leading-5 text-amber-900">Progress is stored only on this device until the student mission database is activated.</p></aside></div>
  </main>;
}
