"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Binoculars, BookOpenCheck, Building2, Check, CheckCircle2, ChevronDown, ClipboardCheck, GraduationCap, Leaf, Printer, ShieldCheck, UserRoundCheck, Users } from "lucide-react";
import { Logo } from "../components/app/logo";

const journey = [
  { step: "01", title: "Confirm readiness", text: "Name the participating school, pilot lead, safeguarding lead, class group and intended start date.", icon: Building2 },
  { step: "02", title: "Prepare people", text: "Invite approved staff, verify mentors and experts, and brief everyone on supervised participation.", icon: Users },
  { step: "03", title: "Protect students", text: "Complete the school’s safeguarding, privacy and guardian-consent preparation before issuing any class code.", icon: ShieldCheck },
  { step: "04", title: "Run one field lesson", text: "Begin with a small, teacher-led biodiversity observation inside an agreed safe fieldwork area.", icon: GraduationCap },
  { step: "05", title: "Review and improve", text: "Teachers check safety and evidence first; approved experts then validate scientific identification.", icon: ClipboardCheck },
];

const roleGuides = [
  { title: "School pilot lead", icon: Building2, items: ["Submit the school application", "Choose one class and teacher", "Approve the fieldwork boundary", "Coordinate launch and feedback"] },
  { title: "Teacher or administrator", icon: BookOpenCheck, items: ["Join through a school invitation", "Prepare consent records", "Issue class codes only when ready", "Review every student submission"] },
  { title: "Mentor", icon: UserRoundCheck, items: ["Apply and complete verification", "Support assigned schools only", "Use supervised learning channels", "Guide projects without grading science"] },
  { title: "Biodiversity expert", icon: Binoculars, items: ["Apply with relevant credentials", "Complete identity and expertise review", "Review teacher-approved evidence", "Record a clear scientific decision"] },
];

const checklist = [
  "School leadership has approved the pilot and named a pilot lead.",
  "A designated safeguarding lead and escalation route are confirmed.",
  "The participating teacher, class and safe fieldwork area are agreed.",
  "Privacy responsibilities and required school agreements have been reviewed.",
  "Guardian/student information and consent materials are ready.",
  "Teachers and administrators know how invitations and class codes work.",
  "Mentors and experts have applied and will not receive access before verification.",
  "The first lesson, equipment, accessibility needs and weather fallback are prepared.",
  "Students understand safe observation, respectful photography and location sensitivity.",
  "The teacher-to-expert review pathway and pilot feedback date are scheduled.",
];

export function PilotOnboarding() {
  const [menuOpen, setMenuOpen] = useState(false);

  return <main className="min-h-screen bg-[#f4f6f1] text-[#15342d]">
    <header className="no-print sticky top-0 z-30 border-b border-white/10 bg-[#0b4436]/95 px-4 py-4 text-white backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Logo /><div className="relative"><button type="button" onClick={() => setMenuOpen((value) => !value)} className="flex items-center gap-2 rounded-lg bg-white/10 px-4 py-2.5 text-[11px] font-bold text-white transition hover:bg-white/15" aria-expanded={menuOpen} aria-controls="pilot-menu" aria-label="Open Pilot onboarding guide menu">Explore this guide <ChevronDown className={`size-4 transition ${menuOpen ? "rotate-180" : ""}`} /></button>{menuOpen && <nav id="pilot-menu" className="absolute left-1/2 top-[calc(100%+10px)] z-40 grid w-52 -translate-x-1/2 gap-1 rounded-xl border border-emerald-900/10 bg-white p-2 text-xs font-bold text-emerald-950 shadow-2xl" aria-label="Pilot onboarding navigation"><a className="rounded-lg px-3 py-2.5 hover:bg-emerald-50" href="#journey" onClick={() => setMenuOpen(false)}>Launch path</a><a className="rounded-lg px-3 py-2.5 hover:bg-emerald-50" href="#roles" onClick={() => setMenuOpen(false)}>Roles</a><a className="rounded-lg px-3 py-2.5 hover:bg-emerald-50" href="#lesson" onClick={() => setMenuOpen(false)}>First lesson</a><a className="rounded-lg px-3 py-2.5 hover:bg-emerald-50" href="#checklist" onClick={() => setMenuOpen(false)}>Checklist</a></nav>}</div><div className="flex items-center gap-2"><Link href="/auth" className="hidden rounded-lg px-4 py-2.5 text-xs font-bold sm:block">Sign in</Link><Link href="/register" className="rounded-lg bg-lime-300 px-4 py-2.5 text-xs font-black text-white">Apply now</Link></div></div></header>

    <section className="bg-[radial-gradient(circle_at_85%_18%,rgba(202,230,105,.22),transparent_27%),linear-gradient(145deg,#0b4436,#153b31)] px-4 py-16 text-white sm:px-7 sm:py-20"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-lime-200/20 bg-white/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-lime-200"><Leaf className="size-4" />PILOT ONBOARDING CENTRE</span><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-tight sm:text-6xl">Take your school from interest to a safe first field lesson.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-emerald-50/75">A practical launch guide for school leaders, teachers, mentors and experts joining GeoMentor Africa.</p><div className="no-print mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-lime-300 px-6 text-sm font-black text-white">Start an application <ArrowRight className="size-4" /></Link><a href="#checklist" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-white/20 bg-white/10 px-6 text-sm font-bold">View launch checklist</a></div></div><aside className="rounded-2xl border border-white/15 bg-white/10 p-6 backdrop-blur"><p className="text-[10px] font-black tracking-[.16em] text-lime-200">BEFORE STUDENTS JOIN</p><div className="mt-5 grid gap-4">{["School approval and named safeguarding lead", "Teacher-led class and consent preparation", "Verified mentor and expert access", "A safe, bounded first learning activity"].map((item) => <div key={item} className="flex gap-3 text-sm leading-6 text-emerald-50"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-lime-300" />{item}</div>)}</div><p className="mt-6 border-t border-white/10 pt-5 text-xs leading-5 text-emerald-100/65">This public guide can be used now. Live onboarding remains subject to the school’s readiness review and platform activation.</p></aside></div></section>

    <section className="scroll-mt-24 px-4 py-16 sm:px-7 sm:py-20" id="journey"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">THE PILOT LAUNCH PATH</p><h2 className="mt-3 max-w-3xl font-serif text-4xl text-emerald-950 sm:text-5xl">Start small, protect trust and learn quickly.</h2><div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{journey.map(({ step,title,text,icon:Icon }) => <article key={step} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-lime-100 text-emerald-800"><Icon className="size-5" /></span><span className="font-mono text-xs font-black text-emerald-700">{step}</span></div><h3 className="mt-5 font-serif text-2xl text-emerald-950">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</div></div></section>

    <section className="scroll-mt-24 bg-white px-4 py-16 sm:px-7 sm:py-20" id="roles"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">WHO DOES WHAT</p><h2 className="mt-3 font-serif text-4xl text-emerald-950 sm:text-5xl">Clear responsibility at every step.</h2><p className="mt-4 text-sm leading-6 text-slate-600">Students join through their school after readiness and consent checks; they never use unrestricted public registration.</p></div><div className="mt-9 grid gap-4 md:grid-cols-2">{roleGuides.map(({ title,icon:Icon,items }) => <article key={title} className="rounded-2xl bg-[#f4f6f1] p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-emerald-800 text-lime-200"><Icon className="size-5" /></span><h3 className="font-serif text-2xl text-emerald-950">{title}</h3></div><ul className="mt-5 grid gap-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm text-slate-600"><Check className="size-5 shrink-0 text-emerald-700" />{item}</li>)}</ul></article>)}</div></div></section>

    <section className="scroll-mt-24 px-4 py-16 sm:px-7 sm:py-20" id="lesson"><div className="mx-auto grid max-w-7xl gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">FIRST BIODIVERSITY LESSON</p><h2 className="mt-3 font-serif text-4xl text-emerald-950 sm:text-5xl">One place. One observation. One complete review cycle.</h2><p className="mt-4 text-sm leading-6 text-slate-600">A focused first session gives the school a safe way to test supervision, evidence quality, GIS capture and scientific review before expanding.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["Before class","Choose a safe site, check consent, weather, accessibility and devices."],["In the field","Teacher demonstrates respectful observation, photography and location capture."],["Back in class","Students add notes; the teacher reviews safety, clarity and evidence quality."],["After review","An approved expert validates the identification and explains the decision."]].map(([title,text], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><span className="font-mono text-xs font-black text-emerald-700">0{index + 1}</span><h3 className="mt-4 font-serif text-2xl text-emerald-950">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</div></div></section>

    <section className="pilot-checklist scroll-mt-24 border-y border-slate-200 bg-white px-4 py-16 sm:px-7 sm:py-20" id="checklist"><div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">PRINTABLE PILOT CHECKLIST</p><h2 className="mt-3 font-serif text-4xl text-emerald-950 sm:text-5xl">Ready to launch?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Confirm every item before a student receives a class code or submits live field evidence.</p></div><button type="button" onClick={() => window.print()} className="no-print inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#0b4436] px-5 text-xs font-black text-white"><Printer className="size-4" />Print checklist</button></div><ol className="mt-8 grid gap-3 sm:grid-cols-2">{checklist.map((item, index) => <li key={item} className="flex gap-4 rounded-xl border border-slate-200 p-4 text-sm leading-6"><span className="grid size-7 shrink-0 place-items-center rounded-md border-2 border-emerald-300 font-mono text-[10px] font-black text-emerald-800">{index + 1}</span>{item}</li>)}</ol><div className="mt-6 grid gap-4 rounded-xl bg-emerald-950 p-6 text-emerald-50 sm:grid-cols-3"><span><small className="block text-[9px] font-black tracking-widest text-lime-300">SCHOOL</small><span className="mt-8 block border-b border-emerald-100/40" /></span><span><small className="block text-[9px] font-black tracking-widest text-lime-300">PILOT LEAD</small><span className="mt-8 block border-b border-emerald-100/40" /></span><span><small className="block text-[9px] font-black tracking-widest text-lime-300">TARGET START DATE</small><span className="mt-8 block border-b border-emerald-100/40" /></span></div></div></section>

    <section className="no-print px-4 py-16 sm:px-7"><div className="mx-auto flex max-w-5xl flex-col items-center rounded-3xl bg-lime-100 px-6 py-12 text-center"><ShieldCheck className="size-10 text-emerald-800" /><h2 className="mt-5 max-w-3xl font-serif text-4xl text-emerald-950">Ready to prepare your pilot?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Schools apply for approval. Mentors and experts apply for verification. Teachers are invited by approved schools, and students join only through supervised class access.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/register" className="rounded-lg bg-[#0b4436] px-6 py-3 text-xs font-black text-white">Apply to join</Link><Link href="/trust" className="rounded-lg bg-white px-6 py-3 text-xs font-black text-emerald-800">Read trust &amp; safety</Link><Link href="/auth" className="px-6 py-3 text-xs font-black text-emerald-800">Sign in</Link></div></div></section>

    <footer className="no-print border-t border-slate-200 bg-white px-4 py-7 sm:px-7"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-slate-500 sm:flex-row sm:items-center"><span className="flex items-center gap-2 font-bold text-emerald-950"><Leaf className="size-4 text-emerald-700" />GeoMentor Africa Pilot Onboarding</span><div className="flex flex-wrap gap-5"><Link href="/">Home</Link><Link href="/pilot">Programme &amp; safety</Link><Link href="/register">Apply</Link><Link href="/portal">My portal</Link></div></div></footer>
  </main>;
}
