import Link from "next/link";
import { ArrowRight, Binoculars, Building2, CheckCircle2, GraduationCap, Leaf, Map, ShieldCheck, Sparkles, UserRoundCheck } from "lucide-react";
import { Logo } from "../components/app/logo";

const audiences = [
  { title: "Schools", text: "Launch a supervised biodiversity programme with safe student access, teacher review and a living school map.", href: "/register", action: "Register your school", icon: Building2 },
  { title: "Students", text: "Join through your school or class code, observe local biodiversity and build practical GIS skills.", href: "/join", action: "Join with a class code", icon: GraduationCap },
  { title: "Mentors", text: "Support assigned schools through structured, teacher-supervised learning—not private student messaging.", href: "/register", action: "Apply as a mentor", icon: UserRoundCheck },
  { title: "Experts", text: "Review evidence and scientific identifications after each record passes the school’s quality gate.", href: "/register", action: "Apply as an expert", icon: Binoculars },
];

const process = [
  ["01", "Observe", "Students record a plant, animal, habitat or conservation activity with evidence and location quality."],
  ["02", "Review", "Teachers check safety and evidence quality before any observation moves to scientific validation."],
  ["03", "Verify", "Approved experts make the final identification decision. AI suggestions remain unverified."],
  ["04", "Map impact", "Schools build a trusted biodiversity map and track learning, habitats and restoration outcomes."],
];

export function PublicLanding() {
  return <main className="min-h-screen bg-[#f4f6f1] text-[#15342d]">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0b4436]/95 px-4 py-4 text-white backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Logo /><nav className="hidden items-center gap-6 text-xs font-bold text-emerald-100/75 md:flex" aria-label="Public navigation"><a href="#how">How it works</a><a href="#people">Who it serves</a><a href="#safety">Safeguarding</a></nav><div className="flex items-center gap-2"><Link href="/auth" className="hidden min-h-10 items-center rounded-lg px-4 text-xs font-bold text-white hover:bg-white/10 sm:inline-flex">Sign in</Link><Link href="/register" className="inline-flex min-h-10 items-center rounded-lg bg-lime-300 px-4 text-xs font-black text-emerald-950">Join the pilot</Link></div></div></header>

    <section className="overflow-hidden bg-[radial-gradient(circle_at_82%_18%,rgba(204,231,109,.24),transparent_25%),linear-gradient(145deg,#0b4436,#153b31)] px-4 py-14 text-white sm:px-7 sm:py-20"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><span className="inline-flex items-center gap-2 rounded-full border border-lime-200/20 bg-white/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-lime-200"><Sparkles className="size-3.5" />AFRICA-LED SPATIAL LEARNING</span><h1 className="mt-6 max-w-3xl font-serif text-5xl leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">Turn every school into a living biodiversity classroom.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-emerald-50/75">GeoMentor Africa connects supervised student fieldwork, GIS mapping, trusted mentors and expert verification—so young people learn by observing and conserving the places around them.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-lime-300 px-6 text-sm font-black text-emerald-950">Register your school <ArrowRight className="size-4" /></Link><Link href="/student" className="inline-flex min-h-12 items-center justify-center rounded-lg border border-white/20 bg-white/10 px-6 text-sm font-bold text-white">Explore student workspace</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs text-emerald-100/70"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-lime-300" />Teacher supervised</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-lime-300" />Expert verified</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-lime-300" />Privacy conscious</span></div></div><div className="relative"><div className="absolute -inset-4 rounded-[2rem] bg-lime-300/10 blur-2xl" /><img src="/og.png" alt="African students and a teacher documenting biodiversity in a school garden" className="relative aspect-[1.91/1] w-full rounded-2xl border border-white/15 object-cover shadow-2xl" /><div className="relative -mt-5 mx-5 grid grid-cols-3 rounded-xl border border-slate-200 bg-white p-4 text-center text-emerald-950 shadow-xl"><span><strong className="block font-serif text-2xl">Field</strong><small className="text-[9px] text-slate-500">OBSERVATION</small></span><span className="border-x border-slate-200"><strong className="block font-serif text-2xl">GIS</strong><small className="text-[9px] text-slate-500">MAPPING</small></span><span><strong className="block font-serif text-2xl">Care</strong><small className="text-[9px] text-slate-500">CONSERVATION</small></span></div></div></div></section>

    <section className="px-4 py-16 sm:px-7 sm:py-20" id="people"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">ONE TRUSTED NETWORK</p><h2 className="mt-3 font-serif text-4xl text-emerald-950 sm:text-5xl">Built for the whole learning ecosystem.</h2><p className="mt-4 text-sm leading-6 text-slate-600">Each person gets the right workspace and only the access their verified role allows.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{audiences.map(({ title,text,href,action,icon:Icon }) => <article key={title} className="flex min-h-64 flex-col rounded-2xl border border-slate-200 bg-white p-6"><span className="grid size-12 place-items-center rounded-xl bg-lime-100 text-emerald-800"><Icon className="size-5" /></span><h3 className="mt-5 font-serif text-2xl text-emerald-950">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p><Link href={href} className="mt-auto flex items-center gap-1 pt-5 text-xs font-black text-emerald-800">{action} <ArrowRight className="size-4" /></Link></article>)}</div></div></section>

    <section className="bg-white px-4 py-16 sm:px-7 sm:py-20" id="how"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">FROM CURIOSITY TO CONSERVATION</p><h2 className="mt-3 font-serif text-4xl text-emerald-950 sm:text-5xl">A clear evidence pathway.</h2><p className="mt-4 text-sm leading-6 text-slate-600">Students learn the full scientific workflow while schools retain supervision and experts retain final verification authority.</p></div><div className="grid gap-3 sm:grid-cols-2">{process.map(([number,title,text]) => <article key={number} className="rounded-2xl bg-[#f4f6f1] p-5"><span className="font-mono text-xs font-black text-emerald-700">{number}</span><h3 className="mt-4 font-serif text-2xl text-emerald-950">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</div></div></div></section>

    <section className="px-4 py-16 sm:px-7 sm:py-20" id="safety"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-3xl bg-[#0b4436] text-white lg:grid-cols-[.85fr_1.15fr]"><div className="p-8 sm:p-10"><ShieldCheck className="size-9 text-lime-300" /><p className="mt-7 text-[10px] font-black tracking-[.18em] text-lime-200">SAFEGUARDING BY DESIGN</p><h2 className="mt-3 font-serif text-4xl">Young people’s safety is not an add-on.</h2><p className="mt-4 text-sm leading-6 text-emerald-50/70">Student access is school-controlled. Mentoring is supervised. Evidence stays private until review, and sensitive locations can be restricted.</p></div><div className="grid gap-px bg-white/10 sm:grid-cols-2">{["School or class-code joining","Required consent records","No unrestricted student messaging","Private evidence storage","Role-based database policies","Auditable review decisions"].map((item) => <div key={item} className="flex items-center gap-3 bg-[#123f34] p-6 text-sm font-semibold"><CheckCircle2 className="size-5 shrink-0 text-lime-300" />{item}</div>)}</div></div></section>

    <section className="px-4 pb-20 sm:px-7"><div className="mx-auto flex max-w-7xl flex-col items-center rounded-3xl border border-emerald-200 bg-lime-50 px-6 py-12 text-center"><span className="grid size-14 place-items-center rounded-2xl bg-emerald-800 text-lime-200"><Map className="size-6" /></span><h2 className="mt-6 max-w-3xl font-serif text-4xl text-emerald-950 sm:text-5xl">Start with one school. Build evidence that can grow across Africa.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-600">Join the pilot as a school, mentor or expert—or enter your teacher-issued class code as a student.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/register" className="rounded-lg bg-[#0b4436] px-6 py-3 text-xs font-black text-white">Apply to the pilot</Link><Link href="/join" className="rounded-lg bg-white px-6 py-3 text-xs font-black text-emerald-800 shadow-sm">Student class code</Link><Link href="/auth" className="rounded-lg px-6 py-3 text-xs font-black text-emerald-800">Sign in</Link></div></div></section>

    <footer className="border-t border-slate-200 bg-white px-4 py-7 sm:px-7"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-slate-500 sm:flex-row sm:items-center"><span className="flex items-center gap-2 font-bold text-emerald-950"><Leaf className="size-4 text-emerald-700" />GeoMentor Africa</span><span>Mentor. Map. Observe. Conserve.</span><div className="flex gap-5"><Link href="/portal">My portal</Link><Link href="/auth">Sign in</Link></div></div></footer>
  </main>;
}
