import Link from "next/link";
import {
  ArrowRight, BadgeCheck, Banknote, Binoculars, Camera, Check,
  CircleDollarSign, FlaskConical, Globe2, GraduationCap, Handshake, Leaf,
  MapPinned, Microscope, ScanLine, School, ShieldCheck, Sparkles, Sprout,
  TreePine, UserRoundCheck,
} from "lucide-react";
import { LandingHeader } from "./LandingHeader";
import { AfricaImpactMap } from "./AfricaImpactMap";

const roles = [
  {
    title: "Schools", eyebrow: "OWN THE LEARNING ENVIRONMENT", icon: School, href: "/register?role=school",
    text: "Register the institution, onboard teachers and students, create field tasks, review evidence and track a living school biodiversity estate.",
    actions: ["Primary, secondary & tertiary", "Teacher-managed student access", "Tasks, gardens, trees & carbon estimates"],
  },
  {
    title: "Geo-Mentors", eyebrow: "ADOPT · GUIDE · VERIFY", icon: UserRoundCheck, href: "/register?role=mentor",
    text: "Graduates, researchers and industry professionals adopt nearby schools, strengthen AI suggestions and guide supervised field learning.",
    actions: ["Discover schools by location", "Review records and join discussions", "Report workshops, GIS Day & field sessions"],
  },
  {
    title: "Geo-Partners", eyebrow: "FUND VISIBLE OUTCOMES", icon: Handshake, href: "/partner",
    text: "Institutions and sponsors fund excursions, seeds, equipment, scholarships and conservation campaigns with geotagged proof of impact.",
    actions: ["Sponsor a school or campaign", "Fund items or recurring programmes", "Follow milestones and public impact reports"],
  },
];

const workflow = [
  { title: "Capture", text: "Photograph a plant or animal. The field app attaches time and location with consent-aware precision.", icon: Camera },
  { title: "Understand", text: "AI returns a suggested identity and useful context—clearly labelled as a suggestion, never a verified fact.", icon: Sparkles },
  { title: "Review", text: "A teacher checks the student evidence, then a Geo-Mentor or specialist confirms, corrects or escalates it.", icon: BadgeCheck },
  { title: "Act", text: "The record becomes part of a school habitat map, a mission, a planting plan or a funded conservation goal.", icon: MapPinned },
];

const impact = [
  { value: "₦100k", label: "student scholarship pathway", note: "Eligibility and partner link to be added", icon: GraduationCap },
  { value: "4-stage", label: "evidence quality pathway", note: "AI → teacher → mentor → specialist", icon: ScanLine },
  { value: "1 map", label: "for learning and stewardship", note: "schools, species, trees and projects", icon: Globe2 },
  { value: "Traceable", label: "partner-funded outcomes", note: "goal, location, updates and evidence", icon: CircleDollarSign },
];

export function PublicLanding() {
  return <main className="min-h-screen bg-[#f2f3ed] text-[#17332c]">
    <LandingHeader />

    <section className="relative isolate overflow-hidden bg-[#082f27] text-white">
      <img src="/biodiversity-fieldwork.png" alt="A student and teacher documenting biodiversity in a supervised school garden" className="absolute inset-0 h-full w-full object-cover object-center opacity-55" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,34,28,.98)_0%,rgba(4,34,28,.87)_42%,rgba(4,34,28,.2)_78%),linear-gradient(0deg,rgba(4,34,28,.72),transparent_45%)]" />
      <div className="relative mx-auto grid min-h-[700px] max-w-[1440px] items-end px-5 pb-10 pt-24 sm:px-8 sm:pb-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24">
        <div className="max-w-3xl">
          <span className="inline-flex items-center gap-2 rounded-full border border-lime-200/20 bg-black/15 px-3 py-2 text-[10px] font-black tracking-[.16em] text-lime-200 backdrop-blur"><Globe2 className="size-4 animate-[spin_14s_linear_infinite]" />A LIVING LEARNING NETWORK FOR AFRICA</span>
          <h1 className="mt-6 font-serif text-5xl leading-[.98] tracking-[-.04em] sm:text-7xl xl:text-[5.6rem]">Map what lives.<br /><span className="text-lime-200">Grow what matters.</span></h1>
          <p className="mt-6 max-w-2xl text-base leading-7 text-emerald-50/78 sm:text-lg">GeoMentor Africa turns school grounds into field laboratories—connecting student discovery, teacher-led learning, professional verification and accountable conservation funding.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register?role=school" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-lime-300 px-6 text-sm font-black text-emerald-950 transition hover:bg-lime-200">Register a school <ArrowRight className="size-4" /></Link><Link href="/observations" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-white/25 bg-black/10 px-6 text-sm font-bold backdrop-blur hover:bg-white/10"><Binoculars className="size-4" />Explore biodiversity</Link></div>
          <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-[11px] font-semibold text-emerald-100/70"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-lime-300" />School-controlled access</span><span className="flex items-center gap-2"><BadgeCheck className="size-4 text-lime-300" />Human verification</span><span className="flex items-center gap-2"><MapPinned className="size-4 text-lime-300" />Location-linked impact</span></div>
        </div>
        <div className="hidden justify-self-end lg:block"><div className="w-[285px] rounded-2xl border border-white/15 bg-[#06271f]/80 p-5 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between"><span className="text-[9px] font-black tracking-[.15em] text-lime-200">LIVE FIELD NOTE</span><span className="size-2 animate-pulse rounded-full bg-lime-300" /></div><div className="mt-5 flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-lime-300 text-emerald-950"><Leaf className="size-5" /></span><div><strong className="text-sm">Possible lantana</strong><small className="mt-1 block text-[10px] text-emerald-100/55">AI suggestion · 62% confidence</small></div></div><div className="mt-5 grid grid-cols-2 gap-2 text-[9px]"><span className="rounded-lg bg-white/[.07] p-3"><b className="block text-emerald-100/50">LOCATION</b><em className="mt-1 block not-italic text-white">Ibadan · generalized</em></span><span className="rounded-lg bg-white/[.07] p-3"><b className="block text-emerald-100/50">NEXT STEP</b><em className="mt-1 block not-italic text-white">Teacher review</em></span></div><Link href="/observations" className="mt-4 flex items-center justify-between border-t border-white/10 pt-4 text-[10px] font-bold text-lime-200">Open record <ArrowRight className="size-3.5" /></Link></div></div>
      </div>
    </section>

    <section className="border-b border-[#dbe1d8] bg-white px-5 py-5 sm:px-8"><div className="mx-auto grid max-w-[1440px] gap-2 sm:grid-cols-2 xl:grid-cols-4">{impact.map(({ value,label,note,icon:Icon }) => <article key={label} className="flex items-center gap-3 px-2 py-3 xl:border-r xl:border-slate-200 xl:last:border-0"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#edf4d4] text-emerald-800"><Icon className="size-[18px]" /></span><div><strong className="font-serif text-xl text-emerald-950">{value}</strong><span className="ml-1.5 text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</span><small className="block text-[9px] text-slate-400">{note}</small></div></article>)}</div></section>

    <section className="px-5 py-20 sm:px-8" id="roles"><div className="mx-auto max-w-[1440px]"><div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">THREE ROLES. ONE ACCOUNTABLE SYSTEM.</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-tight tracking-tight text-emerald-950 sm:text-6xl">Designed around how the programme actually works.</h2></div><p className="max-w-2xl text-sm leading-7 text-slate-600 lg:justify-self-end">Schools remain responsible for young people and learning. Geo-Mentors extend professional capacity. Geo-Partners make high-value activities possible. Teachers and students participate through their registered school.</p></div><div className="mt-10 grid gap-4 xl:grid-cols-3">{roles.map(({ title,eyebrow,icon:Icon,text,actions,href }, index) => <article key={title} className={`group flex min-h-[420px] flex-col overflow-hidden rounded-2xl border p-7 transition hover:-translate-y-1 hover:shadow-xl ${index === 1 ? "border-emerald-900 bg-[#0b4436] text-white" : "border-slate-200 bg-white"}`}><div className="flex items-start justify-between"><span className={`grid size-12 place-items-center rounded-xl ${index === 1 ? "bg-lime-300 text-emerald-950" : "bg-[#edf4d4] text-emerald-800"}`}><Icon className="size-5" /></span><span className={`font-mono text-xs ${index === 1 ? "text-emerald-100/45" : "text-slate-300"}`}>0{index + 1}</span></div><p className={`mt-7 text-[9px] font-black tracking-[.16em] ${index === 1 ? "text-lime-200" : "text-emerald-700"}`}>{eyebrow}</p><h3 className="mt-2 font-serif text-3xl">{title}</h3><p className={`mt-3 text-xs leading-6 ${index === 1 ? "text-emerald-50/65" : "text-slate-500"}`}>{text}</p><ul className={`mt-6 grid gap-3 border-t pt-5 text-[11px] ${index === 1 ? "border-white/10 text-emerald-50/75" : "border-slate-100 text-slate-600"}`}>{actions.map(item => <li key={item} className="flex gap-2"><Check className={`mt-0.5 size-3.5 shrink-0 ${index === 1 ? "text-lime-300" : "text-emerald-600"}`} />{item}</li>)}</ul><Link href={href} className={`mt-auto flex items-center gap-2 pt-7 text-xs font-black ${index === 1 ? "text-lime-200" : "text-emerald-800"}`}>Enter {title.toLowerCase()} pathway <ArrowRight className="size-4 transition group-hover:translate-x-1" /></Link></article>)}</div></div></section>

    <AfricaImpactMap />

    <section className="bg-white px-5 py-20 sm:px-8" id="lab"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">THE BIODIVERSITY LAB</p><h2 className="mt-4 font-serif text-5xl leading-tight text-emerald-950 sm:text-6xl">A field record is the beginning, not the answer.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-600">Every observation keeps its evidence, AI suggestion, reviewer decisions and discussion history. That makes uncertainty visible and turns corrections into learning.</p><Link href="/observations" className="mt-7 inline-flex items-center gap-2 text-xs font-black text-emerald-800">Browse the public organism library <ArrowRight className="size-4" /></Link><div className="mt-9 grid grid-cols-3 gap-2"><span className="rounded-xl bg-emerald-950 p-4 text-white"><TreePine className="size-5 text-lime-300" /><b className="mt-5 block font-serif text-2xl">Plants</b></span><span className="rounded-xl bg-[#dce7b1] p-4 text-emerald-950"><Binoculars className="size-5" /><b className="mt-5 block font-serif text-2xl">Animals</b></span><span className="rounded-xl bg-[#dce8e4] p-4 text-emerald-950"><Microscope className="size-5" /><b className="mt-5 block font-serif text-2xl">Microbial</b></span></div></div><div className="grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200">{workflow.map(({title,text,icon:Icon}, index) => <article key={title} className="grid gap-5 bg-[#f8f9f5] p-7 sm:grid-cols-[70px_1fr]"><span className="grid size-14 place-items-center rounded-2xl bg-white text-emerald-800 shadow-sm"><Icon className="size-6" /></span><div><span className="font-mono text-[9px] font-black text-slate-400">0{index + 1}</span><h3 className="mt-1 font-serif text-3xl text-emerald-950">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p></div></article>)}</div></div></div></section>

    <section className="px-5 py-20 sm:px-8" id="growth"><div className="mx-auto grid max-w-[1440px] overflow-hidden rounded-3xl bg-[#0a352c] text-white lg:grid-cols-2"><div className="p-8 sm:p-12"><div className="flex gap-3"><Sprout className="size-7 text-lime-300" /><Banknote className="size-7 text-lime-300" /></div><p className="mt-8 text-[10px] font-black tracking-[.18em] text-lime-200">PLANT · MONITOR · VALUE</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">From a seedling to a defensible impact record.</h2><p className="mt-5 text-sm leading-7 text-emerald-50/68">Schools tag planted trees, record species, date, survival, diameter and height, and document harvest or non-timber revenue. The platform can estimate biomass and CO₂e for learning and planning.</p><div className="mt-8 rounded-xl border border-amber-200/20 bg-amber-200/10 p-4 text-xs leading-6 text-amber-50"><strong className="block text-amber-200">Carbon estimate ≠ carbon credit.</strong>A saleable credit requires an approved methodology, baseline, additionality, leakage and permanence controls, independent validation and registry issuance.</div></div><div className="grid gap-px bg-white/10 sm:grid-cols-2">{[{title:"Measure",text:"Species, planting date, survival, DBH, height and geotagged evidence.",icon:TreePine},{title:"Estimate",text:"Species- or region-appropriate allometry → dry biomass → carbon → CO₂e.",icon:FlaskConical},{title:"Verify",text:"Versioned assumptions, mentor review and qualified methodology oversight.",icon:BadgeCheck},{title:"Generate value",text:"Track fruit, seedlings, ecosystem services, sponsorship and eligible project revenue.",icon:Banknote}].map(({title,text,icon:Icon}) => <article key={title} className="bg-[#103e33] p-7"><Icon className="size-6 text-lime-300" /><h3 className="mt-7 font-serif text-2xl">{title}</h3><p className="mt-2 text-xs leading-6 text-emerald-50/62">{text}</p></article>)}</div></div></section>

    <section className="bg-[#dce7b1] px-5 py-20 sm:px-8" id="partners"><div className="mx-auto grid max-w-[1440px] items-center gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-800">FUND A GOAL. FOLLOW THE LOCATION. SEE THE IMPACT.</p><h2 className="mt-4 max-w-3xl font-serif text-5xl leading-tight text-emerald-950 sm:text-6xl">Make every contribution visible on the ground.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-emerald-950/65">Geo-Partners can support a school garden, indigenous trees, field equipment, an excursion, mentor teams or student scholarships—then follow evidence, milestones and outcomes.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/partner" className="rounded-md bg-[#0b4436] px-6 py-3.5 text-xs font-black text-white">Explore partner opportunities</Link><Link href="/partner#campaigns" className="rounded-md border border-emerald-900/20 bg-white/50 px-6 py-3.5 text-xs font-black text-emerald-950">View active goals</Link></div></div><div className="rounded-2xl bg-white p-6 shadow-[0_20px_60px_rgba(20,57,45,.12)]"><div className="flex items-center justify-between"><span className="rounded-full bg-emerald-100 px-3 py-2 text-[9px] font-black text-emerald-800">VERIFIED SCHOOL GOAL</span><span className="text-xs font-bold text-slate-400">Oyo, Nigeria</span></div><h3 className="mt-6 font-serif text-3xl text-emerald-950">Restore the school pollinator garden</h3><p className="mt-3 text-xs leading-5 text-slate-500">Seeds, hand tools, field guides and supervised transport for 60 learners.</p><div className="mt-7 flex items-end justify-between"><div><small className="text-[9px] font-black text-slate-400">RAISED</small><strong className="block font-serif text-3xl text-emerald-950">₦680,000</strong></div><span className="text-xs font-black text-emerald-700">68%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><span className="block h-full w-[68%] rounded-full bg-emerald-700" /></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-slate-100 pt-5 text-center"><span><b className="font-serif text-xl">60</b><small className="block text-[8px] text-slate-400">STUDENTS</small></span><span><b className="font-serif text-xl">240</b><small className="block text-[8px] text-slate-400">SEEDLINGS</small></span><span><b className="font-serif text-xl">4</b><small className="block text-[8px] text-slate-400">MILESTONES</small></span></div></div></div></section>

    <section className="bg-[#082f27] px-5 py-20 text-white sm:px-8"><div className="mx-auto flex max-w-[1440px] flex-col items-start justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-[10px] font-black tracking-[.18em] text-lime-200">THE NEXT DISCOVERY CAN START AT YOUR SCHOOL</p><h2 className="mt-4 max-w-4xl font-serif text-5xl leading-tight sm:text-7xl">Build a record of learning, life and measurable care.</h2></div><div className="flex shrink-0 flex-col gap-3 sm:flex-row lg:flex-col"><Link href="/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-lime-300 px-6 text-xs font-black text-emerald-950">Choose your role <ArrowRight className="size-4" /></Link><Link href="/observations" className="inline-flex min-h-12 items-center justify-center rounded-md border border-white/20 px-6 text-xs font-black">Explore the map</Link></div></div></section>

    <footer className="border-t border-white/10 bg-[#082f27] px-5 py-8 text-emerald-100/55 sm:px-8"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-5 text-xs md:flex-row md:items-center"><span className="flex items-center gap-2 font-bold text-white"><Leaf className="size-4 text-lime-300" />GeoMentor Africa</span><p>Mentor. Map. Observe. Conserve.</p><nav className="flex flex-wrap gap-x-5 gap-y-2"><Link href="/observations">Biodiversity</Link><Link href="/partner">Partners</Link><Link href="/pilot">Programme</Link><Link href="/trust">Trust &amp; safety</Link><Link href="/portal">My workspace</Link></nav></div></footer>
  </main>;
}
