import Link from "next/link";
import { AlertTriangle, ArrowRight, CheckCircle2, HelpCircle, KeyRound, Leaf, LockKeyhole, Scale, ShieldCheck, UserCheck } from "lucide-react";
import { Logo } from "../components/app/logo";

const safeguards = [
  "Students join only through a school-managed process or teacher-issued class code.",
  "Mentors and experts must be reviewed and verified before trusted access.",
  "No unrestricted private adult-to-student messaging is permitted.",
  "Student evidence stays private until the school review process allows wider visibility.",
  "Teachers supervise learning activities and remain the first safeguarding contact.",
  "Sensitive species and critical locations may be restricted or withheld entirely.",
];

const faqs = [
  ["Can a student register publicly?", "No. Students use a school or class code and remain pending until the school verifies membership and required consent."],
  ["Does AI identify a species automatically?", "AI may suggest an identification, but it remains unverified. Teachers check evidence and approved experts make scientific decisions."],
  ["Can mentors message students privately?", "No. Mentoring should happen in teacher-supervised school or group spaces."],
  ["Are observation coordinates public?", "No. Access depends on role and sensitivity. Critical locations are withheld and public outputs should be aggregated."],
  ["What happens when consent is withdrawn?", "Future optional processing should stop after verification. The school and platform decide what is deleted, anonymised or lawfully retained."],
  ["Is this policy legal certification?", "No. It describes pilot commitments. Legal, safeguarding and data-processing review is required before live student onboarding."],
];

function Heading({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <div className="max-w-3xl"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">{eyebrow}</p><h2 className="mt-2 font-serif text-4xl text-emerald-950 sm:text-5xl">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{children}</p></div>;
}

export function TrustCentre() {
  return <main className="min-h-screen bg-[#f4f6f1] text-[#15342d]">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0b4436]/95 px-4 py-4 text-white backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Logo /><nav className="hidden items-center gap-5 text-[11px] font-bold text-emerald-100/75 lg:flex" aria-label="Trust centre navigation"><a href="#safeguarding">Safeguarding</a><a href="#privacy">Privacy</a><a href="#consent">Consent</a><a href="#terms">Terms</a><a href="#support">Support</a><a href="#faq">FAQ</a></nav><Link href="/" className="rounded-lg bg-white/10 px-4 py-2.5 text-xs font-bold">Back to home</Link></div></header>

    <section className="bg-[radial-gradient(circle_at_85%_18%,rgba(202,230,105,.22),transparent_27%),linear-gradient(145deg,#0b4436,#153b31)] px-4 py-16 text-white sm:px-7 sm:py-20"><div className="mx-auto max-w-7xl"><span className="inline-flex items-center gap-2 rounded-full border border-lime-200/20 bg-white/10 px-3 py-2 text-[10px] font-black tracking-[.16em] text-lime-200"><ShieldCheck className="size-4" />PUBLIC PILOT COMMITMENTS</span><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-tight sm:text-6xl">Trust, safety and dignity by design.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-emerald-50/75">How GeoMentor Africa intends to protect students, school communities, field evidence and personal data during the pilot.</p><div className="mt-8 flex flex-wrap gap-3 text-xs"><span className="rounded-lg bg-white/10 px-3 py-2">Effective 26 August 2026</span><span className="rounded-lg bg-amber-300 px-3 py-2 font-black text-amber-950">Pilot policy · legal review required before live student onboarding</span></div></div></section>

    <div className="mx-auto max-w-7xl px-4 py-14 sm:px-7">
      <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6"><UserCheck className="size-7 text-emerald-700" /><h2 className="mt-4 font-serif text-2xl">School controlled</h2><p className="mt-2 text-xs leading-5 text-slate-500">Schools approve participation and supervise learning.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><LockKeyhole className="size-7 text-emerald-700" /><h2 className="mt-4 font-serif text-2xl">Least access</h2><p className="mt-2 text-xs leading-5 text-slate-500">Verified roles and private evidence storage limit access.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><Scale className="size-7 text-emerald-700" /><h2 className="mt-4 font-serif text-2xl">Human verification</h2><p className="mt-2 text-xs leading-5 text-slate-500">AI suggestions never become verified records without a human decision.</p></article></section>

      <section className="scroll-mt-24 py-16" id="safeguarding"><Heading eyebrow="CHILD SAFEGUARDING" title="The child’s best interests come first.">GeoMentor Africa is designed for school-supervised learning. Participating organisations remain responsible for safeguarding leads, staff checks, local reporting duties and safe fieldwork.</Heading><div className="mt-8 grid gap-3 sm:grid-cols-2">{safeguards.map((item) => <div key={item} className="flex gap-3 rounded-xl border border-emerald-100 bg-white p-5 text-sm leading-6"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-700" />{item}</div>)}</div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>Immediate concern:</strong> tell a trusted teacher, guardian or the school’s designated safeguarding lead. If someone may be in immediate danger, contact the appropriate local authority. The platform is not an emergency service.</div></section>

      <section className="scroll-mt-24 border-y border-slate-200 py-16" id="privacy"><Heading eyebrow="PRIVACY NOTICE" title="Collect less. Explain clearly. Protect carefully.">This notice reflects privacy-by-design principles. It does not replace the data-processing agreement and role assessment required with each school before accepting live student data.</Heading><div className="mt-8 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl bg-white p-6"><h3 className="font-serif text-2xl">Information we may process</h3><ul className="mt-4 grid gap-2 text-sm leading-6 text-slate-600"><li>• Account, role, school and approval details.</li><li>• Guardian or school consent records.</li><li>• Observation notes, photographs, time and location quality.</li><li>• Review decisions, security and audit events.</li></ul></article><article className="rounded-2xl bg-white p-6"><h3 className="font-serif text-2xl">Why we may use it</h3><ul className="mt-4 grid gap-2 text-sm leading-6 text-slate-600"><li>• Supervised fieldwork and GIS learning.</li><li>• Membership, evidence and identification review.</li><li>• User protection and misuse investigation.</li><li>• School-approved aggregated reporting.</li></ul></article><article className="rounded-2xl bg-white p-6"><h3 className="font-serif text-2xl">Access and disclosure</h3><p className="mt-3 text-sm leading-6 text-slate-600">Access is limited by purpose and verified role. Private student evidence is not intended for public browsing.</p></article><article className="rounded-2xl bg-white p-6"><h3 className="font-serif text-2xl">Retention and deletion</h3><p className="mt-3 text-sm leading-6 text-slate-600">A documented retention schedule, processor list, hosting assessment and deletion procedure must be approved before live student onboarding.</p></article></div><div className="mt-5 rounded-xl bg-emerald-950 p-6 text-sm leading-6 text-emerald-50"><strong className="text-lime-300">Privacy choices:</strong> subject to applicable law and verification, people may request information, access, correction, deletion, restriction, objection, portability or consent withdrawal. Complaints may also be made to the Nigeria Data Protection Commission.</div></section>

      <section className="scroll-mt-24 py-16" id="consent"><Heading eyebrow="CONSENT AND PARTICIPATION" title="Consent is informed, recorded and reversible.">A class code creates a pending request; it does not grant unrestricted access. Each school determines the appropriate authority pathway under applicable law and school policy.</Heading><div className="mt-8 grid gap-4 md:grid-cols-3">{[["01","Explain","Give students and guardians plain-language information about activities, data, risks and choices."],["02","Verify and record","Confirm the responsible adult or school authority and record the applicable decision."],["03","Respect withdrawal","Stop future optional processing and explain what is deleted, anonymised or lawfully retained."]].map(([n,title,text]) => <article key={n} className="rounded-2xl border border-slate-200 bg-white p-6"><span className="font-mono text-xs font-black text-emerald-700">{n}</span><h3 className="mt-4 font-serif text-2xl">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Student assent should be sought in age-appropriate language even where a guardian or school provides formal authority.</p></section>

      <section className="scroll-mt-24 border-y border-slate-200 py-16" id="terms"><Heading eyebrow="PILOT TERMS OF USE" title="Use the platform for learning, evidence and conservation.">These summary terms describe acceptable pilot behaviour. Qualified Nigerian counsel should review final binding terms before commercial or live student launch.</Heading><div className="mt-8 grid gap-4 md:grid-cols-2"><article className="rounded-2xl bg-white p-6"><Scale className="size-6 text-emerald-700" /><h3 className="mt-4 font-serif text-2xl">You agree to</h3><ul className="mt-3 grid gap-2 text-sm leading-6 text-slate-600"><li>• Provide accurate role information.</li><li>• Protect class codes and invitations.</li><li>• Follow safeguarding instructions.</li><li>• Upload only authorised evidence.</li><li>• Respect wildlife, privacy and intellectual property.</li></ul></article><article className="rounded-2xl bg-white p-6"><AlertTriangle className="size-6 text-amber-600" /><h3 className="mt-4 font-serif text-2xl">You must not</h3><ul className="mt-3 grid gap-2 text-sm leading-6 text-slate-600"><li>• Contact students outside supervised channels.</li><li>• Reveal private or sensitive-location data.</li><li>• Harass, impersonate or manipulate evidence.</li><li>• Treat AI output as verified advice.</li><li>• Use the service for surveillance or unlawful activity.</li></ul></article></div></section>

      <section className="scroll-mt-24 py-16" id="support"><Heading eyebrow="SUPPORT AND REPORTING" title="Know where to raise a concern.">Until dedicated operational mailboxes and response commitments are activated, support follows the school-first pilot pathway.</Heading><div className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6"><KeyRound className="size-6 text-emerald-700" /><h3 className="mt-4 font-serif text-2xl">Access problem</h3><p className="mt-2 text-xs leading-5 text-slate-500">Ask your teacher or school administrator to check the class code, invitation, membership or consent.</p><Link href="/portal" className="mt-5 flex items-center gap-1 text-xs font-black text-emerald-800">Check your portal <ArrowRight className="size-4" /></Link></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><ShieldCheck className="size-6 text-emerald-700" /><h3 className="mt-4 font-serif text-2xl">Safety concern</h3><p className="mt-2 text-xs leading-5 text-slate-500">Tell the school’s designated safeguarding lead or a trusted adult immediately.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6"><LockKeyhole className="size-6 text-emerald-700" /><h3 className="mt-4 font-serif text-2xl">Privacy request</h3><p className="mt-2 text-xs leading-5 text-slate-500">Submit through the participating school. A dedicated GeoMentor contact must be activated before live onboarding.</p></article></div></section>

      <section className="scroll-mt-24 rounded-3xl bg-white p-6 sm:p-9" id="faq"><div className="flex gap-3"><HelpCircle className="size-7 text-emerald-700" /><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">PILOT FAQ</p><h2 className="mt-1 font-serif text-4xl">Common safety questions</h2></div></div><div className="mt-7 grid gap-3">{faqs.map(([q,a]) => <details key={q} className="rounded-xl border border-slate-200 p-5"><summary className="cursor-pointer list-none text-sm font-bold">{q}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{a}</p></details>)}</div></section>

      <section className="mt-10 rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[10px] font-black tracking-[.18em] text-slate-400">OFFICIAL REFERENCE POINTS</p><p className="mt-3 text-xs leading-5 text-slate-600">These commitments were informed by official Nigerian materials. Applicability and controller responsibilities must be confirmed for the final operating model.</p><div className="mt-4 flex flex-wrap gap-3"><a className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800" href="https://ndpc.gov.ng/download/nigeria-data-protection-act-2023" target="_blank" rel="noreferrer">Nigeria Data Protection Act 2023</a><a className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800" href="https://www.nigeriarights.gov.ng/files/childrightact.pdf" target="_blank" rel="noreferrer">Child Rights Act</a><a className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800" href="https://www.nigeriarights.gov.ng/files/child%20safeguarding%20policy.pdf" target="_blank" rel="noreferrer">NHRC Child Safeguarding Policy</a><a className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800" href="https://ndpc.gov.ng/resources/" target="_blank" rel="noreferrer">NDPC resources</a></div></section>
    </div>

    <footer className="border-t border-slate-200 bg-white px-4 py-7 sm:px-7"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-slate-500 sm:flex-row sm:items-center"><span className="flex items-center gap-2 font-bold text-emerald-950"><Leaf className="size-4 text-emerald-700" />GeoMentor Africa Trust and Safety Centre</span><span>Pilot policy · effective 26 August 2026</span><div className="flex gap-5"><Link href="/">Home</Link><Link href="/register">Apply</Link><Link href="/auth">Sign in</Link></div></div></footer>
  </main>;
}
