"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Bird, Check, Eye, EyeOff, Filter, Flower2, Leaf, Map as MapIcon, MapPin, ShieldCheck, Sparkles, Trees, Waves } from "lucide-react";
import { Logo } from "../../components/app/logo";

type Layer = "Trees" | "Pollinators" | "Birds" | "Water & soil" | "Conservation";
type Record = { id: string; name: string; scientific: string; layer: Layer; x: number; y: number; status: "Expert verified" | "Teacher reviewed" | "Pending review"; date: string; note: string; sensitive?: boolean };

const layers: Array<{ name: Layer; color: string; icon: typeof Trees }> = [
  { name: "Trees", color: "#177052", icon: Trees }, { name: "Pollinators", color: "#dc7b26", icon: Flower2 },
  { name: "Birds", color: "#5657a6", icon: Bird }, { name: "Water & soil", color: "#2585a6", icon: Waves },
  { name: "Conservation", color: "#9b5d35", icon: Leaf },
];
const records: Record[] = [
  { id: "GMA-0246", name: "Neem", scientific: "Azadirachta indica", layer: "Trees", x: 29, y: 33, status: "Expert verified", date: "23 Aug 2026", note: "Mature shade tree beside the supervised garden path." },
  { id: "GMA-0248", name: "Orange butterfly", scientific: "Danaus sp.", layer: "Pollinators", x: 48, y: 51, status: "Teacher reviewed", date: "24 Aug 2026", note: "Observed feeding near flowering milkweed for four minutes." },
  { id: "GMA-0252", name: "Village weaver", scientific: "Ploceus cucullatus", layer: "Birds", x: 68, y: 27, status: "Expert verified", date: "25 Aug 2026", note: "Two birds moving between trees near the assembly area." },
  { id: "GMA-0257", name: "Garden soil sample", scientific: "School habitat record", layer: "Water & soil", x: 39, y: 69, status: "Pending review", date: "26 Aug 2026", note: "Dark, moist soil beneath leaf litter after rainfall." },
  { id: "GMA-0260", name: "Native flower bed", scientific: "Restoration activity", layer: "Conservation", x: 76, y: 63, status: "Teacher reviewed", date: "26 Aug 2026", note: "Student-planted habitat patch for local pollinators." },
  { id: "GMA-0262", name: "Protected nest site", scientific: "Location restricted", layer: "Birds", x: 58, y: 43, status: "Expert verified", date: "26 Aug 2026", note: "The exact location is withheld to protect wildlife.", sensitive: true },
];

export function SchoolMap() {
  const [visible, setVisible] = useState<Layer[]>(layers.map((item) => item.name));
  const [verifiedOnly, setVerifiedOnly] = useState(false);
  const [selectedId, setSelectedId] = useState(records[0].id);
  const filtered = useMemo(() => records.filter((item) => visible.includes(item.layer) && (!verifiedOnly || item.status === "Expert verified")), [visible, verifiedOnly]);
  const selected = filtered.find((item) => item.id === selectedId) || filtered[0] || null;
  const toggleLayer = (layer: Layer) => setVisible((current) => current.includes(layer) ? current.filter((item) => item !== layer) : [...current, layer]);

  return <main className="min-h-screen bg-[#eef2ed] text-[#15342d]">
    <header className="border-b border-white/10 bg-[#0b4436] px-4 py-4 text-white sm:px-7"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4"><Logo /><div className="flex items-center gap-2"><span className="hidden rounded-full bg-white/10 px-3 py-2 text-[10px] font-black text-lime-200 sm:block">PRIVACY-SAFE GIS</span><Link href="/student" className="rounded-lg bg-white/10 px-4 py-2.5 text-xs font-bold">Student workspace</Link></div></div></header>
    <div className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">SCHOOL BIODIVERSITY MAP</p><h1 className="mt-2 font-serif text-4xl text-emerald-950 sm:text-5xl">Explore what lives around your school.</h1><p className="mt-3 text-sm text-slate-600">Staff School, Ibadan · Project preview · approximate locations only</p></div><div className="flex flex-wrap gap-2"><span className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-xs"><strong className="font-serif text-xl text-emerald-950">{filtered.length}</strong> visible records</span><span className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-xs"><strong className="font-serif text-xl text-emerald-950">3</strong> verified species</span></div></div>
      <div className="mt-6 grid gap-4 xl:grid-cols-[250px_minmax(0,1fr)_320px]">
        <aside className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Filter className="size-5 text-emerald-700" /><h2 className="font-serif text-2xl text-emerald-950">Map layers</h2></div><p className="mt-2 text-[10px] leading-4 text-slate-500">Show or hide biodiversity categories.</p><div className="mt-5 grid gap-2">{layers.map(({ name,color,icon:Icon }) => { const active = visible.includes(name); return <button type="button" key={name} aria-pressed={active} onClick={() => toggleLayer(name)} className={`flex items-center gap-3 rounded-xl border p-3 text-left text-xs font-bold ${active ? "border-emerald-300 bg-emerald-50" : "border-slate-200 text-slate-400"}`}><span className="grid size-8 place-items-center rounded-lg text-white" style={{ backgroundColor: color }}><Icon className="size-4" /></span><span className="flex-1">{name}</span>{active ? <Eye className="size-4" /> : <EyeOff className="size-4" />}</button>; })}</div><label className="mt-5 flex cursor-pointer gap-3 border-t border-slate-200 pt-5 text-xs font-bold"><input type="checkbox" className="size-4 accent-emerald-700" checked={verifiedOnly} onChange={(e) => setVerifiedOnly(e.target.checked)} /><span>Expert-verified records only</span></label><button type="button" onClick={() => { setVisible(layers.map((item) => item.name)); setVerifiedOnly(false); }} className="mt-4 text-[10px] font-black text-emerald-800">Reset filters</button></aside>
        <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><span className="flex items-center gap-2 text-xs font-bold text-emerald-900"><MapIcon className="size-4" />School grounds</span><span className="flex items-center gap-2 text-[9px] font-black text-emerald-700"><ShieldCheck className="size-4" />LOCATIONS GENERALIZED</span></div><div className="relative min-h-[570px] overflow-hidden bg-[#e5eadc] bg-[linear-gradient(30deg,rgba(255,255,255,.45)_12%,transparent_12.5%,transparent_87%,rgba(255,255,255,.45)_87.5%),linear-gradient(150deg,rgba(255,255,255,.45)_12%,transparent_12.5%,transparent_87%,rgba(255,255,255,.45)_87.5%)] bg-[length:54px_94px]">
          <span className="absolute -left-[8%] top-[18%] h-5 w-[120%] rotate-[-8deg] border-y border-slate-300 bg-[#faf9ef]" /><span className="absolute left-[52%] top-[-8%] h-[120%] w-4 rotate-[13deg] border-x border-slate-300 bg-[#faf9ef]" /><div className="absolute left-[17%] top-[23%] h-[48%] w-[45%] rotate-[-5deg] rounded-[44%_35%_40%_30%] border-2 border-emerald-700/50 bg-lime-300/30"><span className="absolute left-[35%] top-[42%] rounded-lg bg-white/75 px-3 py-2 text-[9px] font-black text-emerald-900">SCHOOL GARDEN</span></div><div className="absolute bottom-[8%] right-[8%] h-[22%] w-[25%] rounded-lg border border-slate-400 bg-slate-300/45"><span className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-[9px] font-black text-slate-600">CLASSROOMS</span></div>
          {filtered.map((item) => { const layer = layers.find((entry) => entry.name === item.layer)!; const Icon = layer.icon; return <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} aria-label={`View ${item.name}`} className={`absolute grid size-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-4 border-white text-white shadow-lg transition hover:scale-110 focus:outline-none focus:ring-4 focus:ring-lime-300 ${selected?.id === item.id ? "scale-110 ring-4 ring-lime-300" : ""}`} style={{ left: `${item.x}%`, top: `${item.y}%`, backgroundColor: layer.color }}><Icon className="size-4" />{item.sensitive && <span className="absolute -right-2 -top-2 grid size-5 place-items-center rounded-full bg-amber-300 text-[9px] font-black text-amber-950">!</span>}</button>; })}
          {filtered.length === 0 && <div className="absolute inset-0 grid place-items-center bg-white/55 text-center"><div><EyeOff className="mx-auto size-8 text-slate-400" /><p className="mt-3 text-sm font-bold text-slate-600">No records match these filters.</p></div></div>}<div className="absolute bottom-3 left-3 rounded-lg border border-white/60 bg-white/90 px-3 py-2 text-[9px] font-bold text-slate-600 shadow">Approximate display · not for navigation</div></div></section>
        <aside className="grid gap-4 self-start">{selected ? <article className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-3"><span className="grid size-12 place-items-center rounded-xl bg-lime-100 text-emerald-800"><MapPin className="size-5" /></span><span className={`rounded-full px-3 py-2 text-[9px] font-black ${selected.status === "Expert verified" ? "bg-emerald-100 text-emerald-800" : selected.status === "Teacher reviewed" ? "bg-indigo-100 text-indigo-800" : "bg-amber-100 text-amber-800"}`}>{selected.status}</span></div><p className="mt-5 text-[9px] font-black tracking-[.16em] text-slate-400">{selected.id} · {selected.date}</p><h2 className="mt-2 font-serif text-3xl text-emerald-950">{selected.name}</h2><p className="mt-1 text-xs italic text-slate-500">{selected.scientific}</p><p className="mt-4 text-xs leading-5 text-slate-600">{selected.note}</p><div className="mt-5 rounded-xl bg-slate-50 p-4"><small className="text-[9px] font-black tracking-wider text-slate-400">MAP POSITION</small><strong className="mt-1 block text-xs text-emerald-900">{selected.sensitive ? "Withheld for wildlife protection" : "Generalized school-area coordinate"}</strong></div><Link href="/field" className="mt-5 flex min-h-11 items-center justify-center rounded-lg bg-[#0b4436] px-4 text-xs font-black text-white">Record another observation</Link></article> : <article className="rounded-2xl bg-white p-6 text-sm text-slate-500">Select a visible observation.</article>}<article className="rounded-2xl bg-emerald-950 p-6 text-white"><Sparkles className="size-6 text-lime-300" /><h2 className="mt-4 font-serif text-2xl">Map insight</h2><p className="mt-3 text-xs leading-5 text-emerald-50/70">Most current observations cluster near the school garden. The next mission could compare the garden with the supervised courtyard.</p><div className="mt-4 flex items-center gap-2 text-[10px] font-bold text-lime-300"><Check className="size-4" />Teacher-supervised interpretation</div></article></aside>
      </div>
    </div>
  </main>;
}
