import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Banknote, Bus, GraduationCap, Handshake, MapPin, PackageOpen, School, ShieldCheck, Sprout, TreePine, Users } from "lucide-react";
import { Logo } from "../../components/app/logo";

export const metadata: Metadata = { title:"Geo-Partners", description:"Fund location-linked school biodiversity goals and follow verified impact." };

const campaigns = [
  {title:"Restore a pollinator garden",school:"Staff School · Oyo",raised:"₦680,000",target:"₦1,000,000",progress:68,days:21,icon:Sprout,impact:"240 seedlings · 60 students"},
  {title:"Fund a biodiversity field excursion",school:"Greenfield School · Lagos",raised:"₦410,000",target:"₦750,000",progress:55,days:34,icon:Bus,impact:"45 students · 2 field sites"},
  {title:"Equip a Geo-Mentor field team",school:"3 adopted schools · Kaduna",raised:"₦1.2m",target:"₦2,000,000",progress:60,days:17,icon:PackageOpen,impact:"3 schools · 8 GPS kits"},
];

export default function PartnerPage(){ return <main className="min-h-screen bg-[#f2f3ed] text-[#17332c]"><header className="border-b border-white/10 bg-[#082f27] px-4 py-3.5 text-white sm:px-7"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><Logo /><div className="flex items-center gap-2"><Link href="/" className="hidden px-3 py-2 text-[11px] font-bold text-emerald-100/70 sm:block">Back home</Link><Link href="/register?role=partner" className="rounded-md bg-lime-300 px-4 py-2.5 text-[11px] font-black text-white">Become a partner</Link></div></div></header>
  <section className="bg-[#082f27] px-5 pb-20 pt-16 text-white sm:px-8"><div className="mx-auto grid max-w-[1440px] items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><span className="inline-flex items-center gap-2 text-[10px] font-black tracking-[.18em] text-lime-200"><Handshake className="size-4" />THE GEO-PARTNER NETWORK</span><h1 className="mt-6 max-w-4xl font-serif text-6xl leading-[1.02] sm:text-7xl">Fund the goal.<br />Follow the ground truth.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-emerald-50/68">Support scholarships, school gardens, field excursions, equipment and mentor teams. Every approved goal connects money to a place, milestones, evidence and a public impact report.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#campaigns" className="rounded-md bg-lime-300 px-6 py-3.5 text-xs font-black text-white">Browse verified goals</Link><Link href="/register?role=partner" className="rounded-md border border-white/20 px-6 py-3.5 text-xs font-black">Discuss a partnership</Link></div></div><div className="grid grid-cols-2 gap-3">{[{value:"18",label:"active goals",icon:MapPin},{value:"₦24.6m",label:"funds tracked",icon:Banknote},{value:"46",label:"schools supported",icon:Users},{value:"100%",label:"geotagged milestones",icon:ShieldCheck}].map(({value,label,icon:Icon})=><article key={label} className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><Icon className="size-5 text-lime-300" /><strong className="mt-7 block font-serif text-3xl">{value}</strong><small className="text-[9px] font-black uppercase tracking-wide text-emerald-100/50">{label}</small></article>)}</div></div></section>
  <section className="px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1440px]"><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">WAYS TO PARTICIPATE</p><div className="mt-4 grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><h2 className="font-serif text-5xl leading-tight text-emerald-950">More useful than a logo on a page.</h2><div className="grid gap-3 sm:grid-cols-2">{[{title:"Fund a school goal",text:"Back a defined need with a budget, deadline and measurable outcome.",icon:School},{title:"Sponsor student opportunity",text:"Support the ₦100,000 scholarship pathway or supervised field learning.",icon:GraduationCap},{title:"Provide materials",text:"Seeds, software, field guides, GPS devices, computers and survey tools.",icon:PackageOpen},{title:"Adopt a programme",text:"Support multiple schools, mentor teams, GIS Day or a conservation campaign.",icon:TreePine}].map(({title,text,icon:Icon})=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><Icon className="size-6 text-emerald-700" /><h3 className="mt-6 font-serif text-2xl">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{text}</p></article>)}</div></div></div></section>
  <section className="bg-white px-5 py-20 sm:px-8" id="campaigns"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-700">VERIFIED CAMPAIGNS</p><h2 className="mt-3 font-serif text-5xl text-emerald-950">Goals ready for support.</h2></div><span className="flex items-center gap-2 text-[10px] font-bold text-slate-500"><BadgeCheck className="size-4 text-emerald-700" />Organisers and budgets reviewed before publication</span></div><div className="mt-9 grid gap-4 lg:grid-cols-3">{campaigns.map(({title,school,raised,target,progress,days,impact,icon:Icon})=><article key={title} className="overflow-hidden rounded-2xl border border-slate-200 bg-[#f8f9f5]"><div className="relative h-44 bg-[radial-gradient(circle_at_80%_15%,rgba(205,231,109,.45),transparent_30%),linear-gradient(145deg,#123f34,#326554)]"><Icon className="absolute bottom-[-15px] right-[-10px] size-40 text-white/10" /><span className="absolute left-5 top-5 grid size-12 place-items-center rounded-xl bg-lime-300 text-emerald-950"><Icon className="size-5" /></span><span className="absolute bottom-4 left-5 rounded-full bg-white/90 px-3 py-2 text-[8px] font-black text-emerald-900">VERIFIED ORGANISER</span></div><div className="p-6"><p className="text-[9px] font-bold text-emerald-700">{school}</p><h3 className="mt-2 min-h-16 font-serif text-2xl text-emerald-950">{title}</h3><div className="mt-5 flex items-end justify-between"><span><small className="block text-[8px] font-black text-slate-400">RAISED</small><strong className="font-serif text-2xl">{raised}</strong><em className="ml-1 text-[9px] not-italic text-slate-400">of {target}</em></span><b className="text-xs text-emerald-700">{progress}%</b></div><div className="mt-3 h-2 rounded-full bg-slate-200"><span className="block h-full rounded-full bg-emerald-700" style={{width:`${progress}%`}} /></div><div className="mt-4 flex justify-between text-[9px] text-slate-500"><span>{impact}</span><span>{days} days left</span></div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-950 px-4 py-3 text-xs font-black text-white">View goal <ArrowRight className="size-4" /></button></div></article>)}</div></div></section>
  <section className="px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1440px] overflow-hidden rounded-3xl bg-[#dce7b1] lg:grid-cols-[.8fr_1.2fr]"><div className="p-8 sm:p-10"><p className="text-[10px] font-black tracking-[.18em] text-emerald-800">ACCOUNTABILITY PATHWAY</p><h2 className="mt-4 font-serif text-4xl text-emerald-950">See where support goes.</h2><p className="mt-4 text-sm leading-7 text-emerald-950/65">Campaign owners post evidence and expenditure updates against agreed milestones. Completed goals produce a public impact report.</p></div><div className="grid gap-px bg-emerald-950/10 sm:grid-cols-2">{["Verified organiser and location","Goal, target and budget breakdown","Geotagged milestone evidence","Updates, expenditure and impact report"].map((item,i)=><div key={item} className="flex gap-3 bg-[#e5edc4] p-7"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-emerald-900 text-[9px] font-black text-white">{i+1}</span><strong className="text-sm text-emerald-950">{item}</strong></div>)}</div></div></section>
  </main>}
